### ISSUE TITLE
[Feature]: Add Login and Registration features

### ISSUE THREAD

**Issue by mattiapitossi** [dcapal/dcapal#195]
**Background**

DcaPal currently supports portfolio export, but this feature doesn't provide a seamless user experience. Users face challenges due to the lack of synchronization across devices, necessitating manual portfolio transfers. Additionally, the absence of personalized user areas in the app restricts users from effectively managing and engaging with their portfolios.

The objective is to introduce a Single Sign-On (SSO) solution in our application for user login and registration, addressing the current limitation where users cannot sign up and consequently cannot save their portfolios. This update aims to enhance user experience by providing data persistence and robust data protection.

**Requiremens**

1. Explore SSO integration solutions
2. Handle Data (Data Protection) and look for E2EE solutions
3. UI/UX offers a smooth Login/Registration funnel
4. Add E2E testing

**ACs**

- Successful integration of SSO for login and registration.
- Compliance with data protection regulations.
- No critical bugs or security vulnerabilities post-implementation.

**Useful Links**
[https://www.dolthub.com/blog/2023-11-08-building-sso-for-your-web-app/](url)

**Comment by leonardoarcari** [comment]
Sounds like a great plan to me, go for it! 💪 

About E2EE, I came across this document by Google. Tl;dr it might be an overkill and get in the way of delivering a great product in a timely manner. We might get away with simpler privacy solutions, but I'm happy to hear your thoughts on that: https://web.dev/learn/privacy/encryption?hl=it
